### ISSUE TITLE
MODISSubsets stalling for large numbers of points

### ISSUE THREAD

**Issue by ethanwhite** [seantuck12/MODISTools#10]
First - thanks for providing this great tool. It definitely makes working with the MODIS data easier.

I've been using `MODISSubsets` to try to download data for ~5000 locations. I've attempted to run it 3 times in the last three days and it has stalled between 50 and 1100 locations depending on the run. When it stalls it permanently displays something like:

```
Getting subset for location 70 of 5464...
```

and never restarts. This is on Ubuntu 15.04, R 3.2.1.

I looked around for information on rate limiting for the webservice and didn't see anything right away.

Any ideas about what might be going on and/or how to solve it.

**Comment by seantuck12** [comment]
Hi Ethan, thanks for your feedback. It is odd that the call permanently stalls on a subset, I've not seen this behaviour before. Access to the server seems to drop in many ways, for reasons I don't fully understand – we've tried to catch what we can. I'll speak to folks at ORNL DAAC and report back with anything informative. Regarding your suggestion in #11, I think it would be a great idea for MODISSubsets to check for any downloads in SaveDir to avoid duplication. I'll add this to our development branch now, thanks for the suggestion.

**Comment by ethanwhite** [comment]
My last few runs have all stopped part way due to access to the server dropping, but every time I've received a nice clear error message. I'm guessing it was either a short window of some unique server issue or the queue for data just happened to be really long or something, so you can go ahead and close this if you'd like.

Thanks again for the great tool and the quick responses to my questions and issues.

**Comment by ethanwhite** [comment]
Still no more issues after another weeks for of runs, so I'm going to go ahead and close this one. Thanks!
