### ISSUE TITLE
Only download data not currently in SaveDir

### ISSUE THREAD

**Issue by ethanwhite** [seantuck12/MODISTools#11]
Following `MODISSubsets` stalling out as described in #10, I reran the script that called it on the same machine. It appeared that `MODISSubsets` re-requested and re-downloaded all of the data including the files that had already been successfully downloaded. If that impression is correct, I think it would be useful to have `MODISSubsets` check to see if the data already exists in the specified `SaveDir` and only request and download data that is not already present. This would be useful for easily recovering from large requests that fail for any reason.

**Comment by helenphillips** [comment]
Hi Ethan, thanks for the comment! We have a function, UpdateSubsets, which checks what data has already been downloaded into the working directory, and outputs a dataframe of undownloaded sites which can be fed back into MODISSubsets.  Sean and I are currently discussing ideas on how to improve MODISTools, so maybe we should think about merging UpdateSubsets into MODISSubsets.

**Comment by ethanwhite** [comment]
Thanks @helenphillips. I'd missed `UpdateSubsets` in the documentation and am happy to add an extra line to handle this. It doesn't seem to be working for me at the moment, but I'll open another issue to discuss that. Thanks!
