### ISSUE TITLE
Best way to handle explicilty spatio-temporal data?

### ISSUE THREAD

**Issue by ethanwhite** [seantuck12/MODISTools#14]
I'm using MODISTools to combine MODIS data with biological data that is both spatially and temporally explicit. E.g.,:

```
lat,long,year,richness
25.1,-81.1,2000,28
25.1,-81.1,2001,32
26.2,-80.5,2000,42
26.2,-80.5,2001,38
```

I'm trying to figure out the best way to add a column(s) to this data frame that includes vegetation indices (e.g., NDVI), where the value of NDVI is specific to both the geographic coordinates and the year (eventually being able to only include date for a specific portion of the year).

I originally used `MODISSubsets` to download the entire time-series (all years) for each location, but I'm open to downloading individual years (or parts of years) separately. Basically I'm just looking for a little expert guidance on the best way to accomplish this. Thanks in advance (and thanks again for all the help you've already provided) and apologies if I've missed something obvious in the docs.

**Comment by helenphillips** [comment]
Assuming I've understood correctly, the easiest way would be to append a start.date column to the dataset submitted to the MODISSubsets function (specifying StartDate = TRUE), in either POSIXt format, for a specific date range, or the year only, for the entire year's data. 

MODISSubsets downloads each unique line individually so will be able to handle all spatially and temporally explicit data.  MODISSummaries will then append the VI data to the original dataframe, and save as a csv file with a VI column (or multiple, if multiple VIs were inputted into MODISSummaries). 

Hope that helps! Potentially we need to go through help files and make them a bit clearer....

**Comment by ethanwhite** [comment]
Thanks for the help. So, just to make sure I understand, my example data would then look something like:

```
lat,long,year,richness,start.date,end.date
25.1,-81.1,2000,28,2000,2000
25.1,-81.1,2001,32,2001,2001
26.2,-80.5,2000,42,2000,2000
26.2,-80.5,2001,38,2001,2001
```

and this gets passed to MODISSubsets, MODISSubsets downloads one file for each year-coordinate pair combination, and MODISSummaries will assemble those values back to the original data frame?

**Comment by seantuck12** [comment]
Yes, that should give you what you need. It's the simplest way but requires you to download again.

If you'd rather not download, an alternative would be to aggregate the data within each download file by year. You could work out which rows in each data file should be grouped to get your temporally-explicit subsets by extracting the year from each MODIS acquisition date, e.g. `A2000049`. I can elaborate on this if it's not clear?

**Comment by ethanwhite** [comment]
Thanks @helenphillips and @seantuck12. I did the new download yesterday and will hopefully get it all linked up today.
