### ISSUE TITLE
GetProducts error

### ISSUE THREAD

**Issue by jsta** [seantuck12/MODISTools#17]
GetProducts() does not appear to be working. I have pasted the command results and my sessioninfo below. Maybe some links have changed? There is a big banner on the DAAC website that says: "The LP DAAC website has recently been updated. Please check your bookmarks for outdated or broken links."

    library(MODISTools)
    GetProducts()
> Error in GetProducts() : 
  Can't call method "prepare" on an undefined value at /var/www-modis/cgi-bin-MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl line 91.

    sessionInfo()
> R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.10

> locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
[1] MODISTools_0.94.6

> loaded via a namespace (and not attached):
[1] tools_3.2.1    RCurl_1.95-4.7 bitops_1.0-6   XML_3.98-1.3

**Comment by seantuck12** [comment]
I'm afraid I am unable to recover the same error message. All web service request methods are running fine on my machine (OS X). I'm not sure what is happening here: what 'prepare' method is being called, or the significance of line 91 (not a relevant section in the web service definition language for `GetProducts`). Are you still getting the same error?

I will ask the web service maintainers about any website changes, but I suspect this will not be an issue because the web service is hosted by ORNL DAAC not LP DAAC.

**Comment by jsta** [comment]
It mysteriously works now. Maybe I had some namespace conflict or something.

**Comment by seantuck12** [comment]
Odd. I don't see anything unusual in your session info. If you find out what was the cause I'd be interested to know.

**Comment by andriaz** [comment]
i got the same error today

**Comment by cmzambranat** [comment]
I got the same error today:
```
> GetProducts()
Error in GetProducts() : 
Can't call method "prepare" on an undefined value at /var/www-modis/cgi-bin-MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl line 91.
```

However, I solved the problem by loading ```library(RCurl)```.  Seems that the OmegaHat website doesn't have the ```RCurl``` package anymore.

**Comment by seantuck12** [comment]
I've changed the package namespace to try and deal with this issue. Let me know if it persists.

**Comment by cmzambranat** [comment]
Just updated the package and now works perfectly. Thanks!
```
> library(MODISTools)
> GetProducts()
 [1] "MCD12Q1"    "MCD12Q2"    "MCD43A1"   
 [4] "MCD43A2"    "MCD43A4"    "MOD09A1"   
 [7] "MOD11A2"    "MOD13Q1"    "MOD15A2"   
[10] "MOD15A2GFS" "MOD16A2"    "MOD17A2_51"
[13] "MOD17A3"    "MYD09A1"    "MYD11A2"   
[16] "MYD13Q1"    "MYD15A2"  
```
