### ISSUE TITLE
Unavailable datasets

### ISSUE THREAD

**Issue by jsta** [seantuck12/MODISTools#18]
I would like to pull images from the MOD09GQ dataset. Is there any interest in adding the ability to pull images over http from the LP DAAC data pool? I see that the [ModisDownload](http://r-gis.net/?q=ModisDownload) script and [pyModis](http://pymodis.fem-environment.eu/index.html) enables this functionality.

**Comment by seantuck12** [comment]
Sorry for the delayed response. I've taken some time to think about this: I've added it to my list of longer term development ideas, as it would be worthwhile including a greater list of products, but I want to prioritise improving the existing tools first. I've set up an [organisation board](https://trello.com/b/sKegqFsQ) so people can see and suggest ideas on our development roadmap.
