### ISSUE TITLE
Add a new MODIS product (MOD44B)

### ISSUE THREAD

**Issue by lsaravia** [seantuck12/MODISTools#19]
I am interested to work with the MOD44B product, and I see is not in the list you get with GetProducts(), is there any procedure to add a product?

Thanks!

**Comment by seantuck12** [comment]
I’m afraid I have no immediate plans to add access to other products via MODISTools. MODISTools accesses the ORNL DAAC data archive using their [web service](https://daac.ornl.gov/MODIS/MODIS-menu/modis_webservice.html). Only a subset of their products are available using this web service. I have considered expanding MODISTools to incorporate more methods that access other data, but as it stands the entire package is built around this web service. It would be a major development and unfortunately I do not have the time right now. Sorry about that! I would of course welcome contributions from anybody else on this.
