### ISSUE TITLE
Add QualityCheck option for MOD16A2 product

### ISSUE THREAD

**Issue by markjohnsonubc** [seantuck12/MODISTools#20]
MOD16A2 = c(-32767,32700, 32767),          # For the 8-day and monthly ET/LE/PET/PLE, annual LE/PLE

See details for these values at bottom of pg 2 of [MOD16 description] http://goo.gl/Cp8QbO ftp://ftp.ntsg.umt.edu/pub/MODIS/NTSG_Products/MOD16/MOD16_global_evapotranspiration_description.pdf

**Comment by seantuck12** [comment]
I've added this capability now. Thanks very much for providing the information. Note that the MOD16A2 quality control (QC) information used in `QualityCheck` is not the same as the (correct) band information you kindly provided. The QC band is the same as that used for LAI products, and the first bit of information is used to differentiate good and bad quality pixels (see [MODLAND_QC bits](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mod15a2))–so setting `QualityThreshold=0` will summarise the data using only good quality pixels. (Apologies for the delay, I'm busy finishing my PhD).
