### ISSUE TITLE
MODAPS?

### ISSUE THREAD

**Issue by masalmon** [seantuck12/MODISTools#23]
I am interested in "Aqua level 2 atmospheric product" (MOD04/MYD04) that seems to be provided through https://ladsweb.nascom.nasa.gov/data/api.html I understand that MODISTools does not provide access to these data, but do you know any R package that does? Thanks!

**Comment by jsta** [comment]
@masalmon I have not used it myself but maybe you can use `rts::ModisDownload()`?

**Comment by masalmon** [comment]
Thanks, I'll have a look at that! :grinning:

**Comment by masalmon** [comment]
It does not seem to include "MOD04/MYD04" after all.

**Comment by masalmon** [comment]
Well MODISTools is going to get a sibling: I have started working on a package for the LAADS API: https://github.com/masalmon/laads

**Comment by seantuck12** [comment]
All the best with your package development, @masalmon. I will mention it in MODISTools readme. If you'd like to coordinate the development of the two in any way, feel free to get in touch. I'm really just maintaining MODISTools now, as I don't have as much time to commit anymore.

**Comment by masalmon** [comment]
Nice, thanks! I already mention MODISTools in the README of laads. :smile: 

I'll submit laads to rOpenSci when it's ready. Why not submit MODISTools (I guess having only little time is a good answer)? Cf https://github.com/ropensci/onboarding I'd be happy to help!
