### ISSUE TITLE
API link may be broken

### ISSUE THREAD

**Issue by Mkamar** [seantuck12/MODISTools#24]
Function **GetProducts()** gives :
Error in GetProducts() : Application error

According to : http://daac.ornl.gov/MODIS/MODIS-menu/modis_webservice.html the wsdl file has been updated _( though the update date is in may I attest that the library was working correctly until a few days ago but something changed today or very recently)_

Inspecting the new wsdl file the new API seems to be located at :

http://daacmodis.ornl.gov/cgi-bin/MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl

When I tried changing the url myself the function worked normally. 

If this is indeed a broken link I suspect it is spread across the entire library. 
Suggestion : Make link read from a config file

**Comment by ajpelu** [comment]
I got the same error and I noticed in the [web](http://daac.ornl.gov/MODIS/MODIS-menu/modis_webservice.html) that the MODIS Web Service has updated the link. But, How to change the url in the function `GetProducts() `? Any suggestions @Mkamar? 

Thanks

**Comment by seantuck12** [comment]
Yes, folks at ORNL let me know about this change over the weekend. It has just come into effect. I've updated the link to the web service and all is working fine again.
