### ISSUE TITLE
Error in GetProducts() : Application error

### ISSUE THREAD

**Issue by earthcli** [seantuck12/MODISTools#25]
I have got an error recently.
GetProducts()
#Error in GetProducts() : Application error
would you fix it ?

One possible source of errors is the recently instated requirement for login info when programmetically downloading MODIS data. This could potentially cause some unexpected errors for a package like MODISTools. I don't know if this is the case here, but it should atleast be considered. – Mikkel Lydholm Rasmussen 16 hours ago

**Comment by seantuck12** [comment]
It was caused by ORNL changing the location of the web service end point, but it has now been fixed. Install the latest version of MODISTools on GitHub for the fix. A new version has been submitted to CRAN, so should be live very soon. The latest version is 0.95.0.
