### ISSUE TITLE
Why should the Size must be integers?

### ISSUE THREAD

**Issue by earthcli** [seantuck12/MODISTools#26]
In the new version of MODISTools, with MODISSubset function for download, If Size is not two dimensions or not integers, stop with error.
Why should the Size must be integers?
May be  some one need to get a 1.5km*1.5km square grid?

**Comment by seantuck12** [comment]
Unfortunately the MODIS [web service](https://daac.ornl.gov/MODIS/MODIS-menu/modis_webservice.html) only allows integers for Size (see KmAboveBelow and KmLeftRight in web service description). This has always been the case.
