### ISSUE TITLE
'creating vignettes' ERROR

### ISSUE THREAD

**Issue by AbelGalois** [seantuck12/MODISTools#27]
"* installing the package to build vignettes
* creating vignettes ... ERROR
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'UsingMODISTools.tex' failed.
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted
Error: Command failed (1)"

Hi, I tried to install MODISTools from Github today, but suffered an error above. I cannot figure out the reason but re-install the package successfully by setting the 'build_vignettes' FALSE.

**Comment by earthcli** [comment]
may be you should first install LaTex.

**Comment by AbelGalois** [comment]
Hi, earthcli! Thanks. I will try that. 
But I am not sure if there is any difference when I set the 'build_vignettes' FALSE.

**Comment by earthcli** [comment]
there is no trouble for use with build_vignettes=FALSE,  if you do need to see the examples.
and now it can be installed from cran directly.

**Comment by AbelGalois** [comment]
Yes, it could be installed from CRAN now. Many thanks!
