### ISSUE TITLE
GetProducts() error on OSX

### ISSUE THREAD

**Issue by khufkens** [seantuck12/MODISTools#29]
I'm getting an error in OSX when trying to query pretty much anything from the server.

GetProducts() results in a rather non descript:
Error in GetProducts() : Application error

The code works fine on my workstation (Ubuntu Linux 14.04, most recent R release).
Any ideas?

Running:
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)
on a MacBook Pro (Retina, 13-inch, Mid 2014)

**Comment by seantuck12** [comment]
Which version of MODISTools are you using? If earlier than 0.95.0, you'll need to update to the latest package version.

**Comment by khufkens** [comment]
This is not on CRAN yet I assume as I just installed through the package manager and I'm stuck < 0.95.

**Comment by khufkens** [comment]
Works using a github install. I do get this error on the build of the vignettes however.

* creating vignettes ... ERROR
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'UsingMODISTools.tex' failed.
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted

Builds clean without it. Consider it closed, functionality wise. Might want to look at the docs.

**Comment by seantuck12** [comment]
0.95.0 is on CRAN, so I'm not sure why this was not available to you. I will close this issue and open a new one for the vignette build error.

**Comment by khufkens** [comment]
Ah, I updated R and now it's resolved. Sorry about this, I'm normally on linux and used to a system that's always up to date. Got to love decent package management. Anyway, sorry about this.
