### ISSUE TITLE
Errors when running functions

### ISSUE THREAD

**Issue by gerlis22** [seantuck12/MODISTools#34]
I'm trying to run most of the function and get the following error:

> Space required after the Public Identifier
> SystemLiteral " or ' expected
> SYSTEM or PUBLIC, the URI is missing
> Error: 1: Space required after the Public Identifier
> 2: SystemLiteral " or ' expected
> 3: SYSTEM or PUBLIC, the URI is missing

For example the GetDates function:

`GetDates(Lat=51.41363, Long=-0.64875, Product="MOD13Q1")`

My R session info:

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: macOS Sierra 10.12.3
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] MODISTools_0.95.0
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.2    RCurl_1.95-4.8 bitops_1.0-6   XML_3.98-1.5

**Comment by qiaoqiaohe** [comment]
This is because the http://daacmodis.ornl.gov/cgi-bin/MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl has moved to https://daacmodis.ornl.gov/cgi-bin/MODIS/GLBVIZ_1_Glb_subset/MODIS_webservice.pl 
Unfortunately, the original is hard coded.

**Comment by seantuck12** [comment]
Others have provided a fix for this issue (pull requests [#36](https://github.com/seantuck12/MODISTools/pull/36) and [#37](https://github.com/seantuck12/MODISTools/pull/37)). I will update the CRAN version as soon as I can.
